Задание 6. Добавлена функциональность регистрации пользователя
gpb-it-factory/molchanova-middle-service pull request #4
Opened 2024-06-18 23:52 UTC by molchmd

2024-06-19 06:43 UTC, DirtyRamirez commented on src/main/java/ru/molchmd/minibank/middle/client/mock/UsersRepository.java
> +    private final Map<Long, UUID> usersRepository_Id_UUID = new ConcurrentHashMap<>();
в код стайле у нас кемлКейс а не подчеркивания

2024-06-19 06:45 UTC, DirtyRamirez commented on src/main/java/ru/molchmd/minibank/middle/client/mock/UsersRepository.java
> +    private final Map<Long, UUID> usersRepository_Id_UUID = new ConcurrentHashMap<>();
и в некоторых местах тоже было

2024-06-19 06:45 UTC, DirtyRamirez requested changes
поправь плз код стайл, в остальном хорошо!

2024-06-19 16:06 UTC, molchmd commented on src/main/java/ru/molchmd/minibank/middle/client/mock/UsersRepository.java
> +    private final Map<Long, UUID> usersRepository_Id_UUID = new ConcurrentHashMap<>();
Исправила

2024-06-20 08:41 UTC, DirtyRamirez approved these changes
ship it:)

2024-06-20 14:17 UTC, merged